export const themes = [
  {
    id: "one",
    bg: "/src/assets/img1.jpg",
    text: "text-white",
    text_sc: "text-black",
    accent: "text-white/70",
    icon: "fa-mountain-sun",
  },
  // {
  //   id: "two",
  //   bg: "/src/assets/img2.jpg",
  //   text: "text-white",
  //   text_sc: "text-black",
  //   accent: "text-orange-200/70",
  //   icon: "fa-person-skiing",
  // },
  {
    id: "four",
    bg: "/src/assets/img4.jpg",
    text: "text-white",
    text_sc: "text-white",
    accent: "text-white/70",
    icon: "fa-umbrella-beach",
  },
  // {
  //   id: "five",
  //   bg: "/src/assets/img5.jpg",
  //   text: "text-white",
  //   accent: "text-white/70",
  //   icon: "fa-feather-pointed",
  // },
  {
    id: "six",
    bg: "/src/assets/img6.jpg",
    text: "text-white",
    accent: "text-white/70",
    icon: "fa-fish",
  },
  // {
  //   id: "seven",
  //   bg: "/src/assets/img7.jpg",
  //   text: "text-white",
  //   accent: "text-white/70",
  //   icon: "fa-volcano",
  // },
  // {
  //   id: "eight",
  //   bg: "/src/assets/img8.jpg",
  //   text: "text-white",
  //   accent: "text-white/70",
  //   icon: "fa-igloo",
  // },{
  //   id: "nine",
  //   bg: "/src/assets/img9.jpg",
  //   text: "text-white",
  //   accent: "text-white/70",
  //   icon: "fa-person-skating",
  // },
];